---
- name: Install Homebrew packages
  ansible.builtin.include_tasks: homebrew.yml

- name: Install ghostty
  ansible.builtin.include_role:
    name: jahrik.ghostty

- name: Install and configure zsh
  ansible.builtin.include_role:
    name: jahrik.zsh

- name: Install nvim
  ansible.builtin.include_role:
    name: jahrik.nvim
